[[libfdk_aac]]
arch = "aarch64"
git-tree-sha1 = "67723a86975c82b43f01cda306999b382d3435f0"
os = "macos"

    [[libfdk_aac.download]]
    sha256 = "fafc080a094f44c002c50391208e417b26f1ce2d0dc3e2d7950b047473a13a97"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v2.0.3+0/libfdk_aac.v2.0.3.aarch64-apple-darwin.tar.gz"
[[libfdk_aac]]
arch = "aarch64"
git-tree-sha1 = "36e8b47185e1b4491d14b94b1a5447fc27cdda56"
libc = "glibc"
os = "linux"

    [[libfdk_aac.download]]
    sha256 = "e51cd90e6894c36d624e031312671780bf3526248f8fc3a181f1f960dd43559b"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v2.0.3+0/libfdk_aac.v2.0.3.aarch64-linux-gnu.tar.gz"
[[libfdk_aac]]
arch = "aarch64"
git-tree-sha1 = "a1410fbb0f239ad68c876afadcdbdaeb2d7598e4"
libc = "musl"
os = "linux"

    [[libfdk_aac.download]]
    sha256 = "172cf46dc659d404d2006c5d28035d86074d2c09cb3dba37334334df63d6abb6"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v2.0.3+0/libfdk_aac.v2.0.3.aarch64-linux-musl.tar.gz"
[[libfdk_aac]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bd62a2213c60da7827f247663d2082af1a215ba5"
libc = "glibc"
os = "linux"

    [[libfdk_aac.download]]
    sha256 = "097bc42de7791761bd29089a08b5e7a4449619d1e91417ed4c25d7a1e8d8a6ec"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v2.0.3+0/libfdk_aac.v2.0.3.armv6l-linux-gnueabihf.tar.gz"
[[libfdk_aac]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8a42b34d46457c08dde0ccfd4272941c3c3fabc6"
libc = "musl"
os = "linux"

    [[libfdk_aac.download]]
    sha256 = "d961eff4480294cdb6639a80ccb933e741b527a2255737a1cd6eb40f1b922c67"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v2.0.3+0/libfdk_aac.v2.0.3.armv6l-linux-musleabihf.tar.gz"
[[libfdk_aac]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "049099713aa450837ea29b51da98d14e705e121b"
libc = "glibc"
os = "linux"

    [[libfdk_aac.download]]
    sha256 = "0e0362d876fcdff50375f3854be104104dc611676ed573afc2af38e8f8d64a74"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v2.0.3+0/libfdk_aac.v2.0.3.armv7l-linux-gnueabihf.tar.gz"
[[libfdk_aac]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f2ff69c72928f961f67e8ba9c7f10d204173146f"
libc = "musl"
os = "linux"

    [[libfdk_aac.download]]
    sha256 = "7286dcbbb5f29461484ad6bf6e746b12a49e2f2fd250ac56e8227d82f465a802"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v2.0.3+0/libfdk_aac.v2.0.3.armv7l-linux-musleabihf.tar.gz"
[[libfdk_aac]]
arch = "i686"
git-tree-sha1 = "48e9979b4698f02b2b02b5b86e6a189791e1981d"
libc = "glibc"
os = "linux"

    [[libfdk_aac.download]]
    sha256 = "ac272b98a2d7bb0d4706085ac7fe364b52183c80811afead33471a6804c81468"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v2.0.3+0/libfdk_aac.v2.0.3.i686-linux-gnu.tar.gz"
[[libfdk_aac]]
arch = "i686"
git-tree-sha1 = "a38fc5698ca2b3216e73678ef10f89eeaa37ccdb"
libc = "musl"
os = "linux"

    [[libfdk_aac.download]]
    sha256 = "439273c557719b97bbc1e7932bfbe830b387ce58c6efcc6b826a0cf3e1154a3e"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v2.0.3+0/libfdk_aac.v2.0.3.i686-linux-musl.tar.gz"
[[libfdk_aac]]
arch = "i686"
git-tree-sha1 = "ae5653b84a17e570c546e59781be97cfc1425fb6"
os = "windows"

    [[libfdk_aac.download]]
    sha256 = "e97d6f4aa41f9785a83c5badb360a0a649c167ae817717a340defe40ce05ae21"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v2.0.3+0/libfdk_aac.v2.0.3.i686-w64-mingw32.tar.gz"
[[libfdk_aac]]
arch = "powerpc64le"
git-tree-sha1 = "9aa37c9946cd1bef623c62efcaf3c40a2133d198"
libc = "glibc"
os = "linux"

    [[libfdk_aac.download]]
    sha256 = "f304e1b77487ebbc472602c1f831fbd05d11231ab55fb7ecaeb087a0fb06fb8f"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v2.0.3+0/libfdk_aac.v2.0.3.powerpc64le-linux-gnu.tar.gz"
[[libfdk_aac]]
arch = "x86_64"
git-tree-sha1 = "581ff6ab4dc643b0b8cd38bf534858ea64ac3813"
os = "macos"

    [[libfdk_aac.download]]
    sha256 = "91b68196c8981270d600df12617f03213a8c369d4abad2d4fedd9bde2bec1f3b"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v2.0.3+0/libfdk_aac.v2.0.3.x86_64-apple-darwin.tar.gz"
[[libfdk_aac]]
arch = "x86_64"
git-tree-sha1 = "cf5d5f8a6109be3f9c460a39768f57a3e53ff11d"
libc = "glibc"
os = "linux"

    [[libfdk_aac.download]]
    sha256 = "11bdaaa77b1b45aa5801b5b9adb596e2e0a5c44a545d98079a6a72aae9daa64a"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v2.0.3+0/libfdk_aac.v2.0.3.x86_64-linux-gnu.tar.gz"
[[libfdk_aac]]
arch = "x86_64"
git-tree-sha1 = "6b3567682e0013cc3ac328c207512d67c6699d76"
libc = "musl"
os = "linux"

    [[libfdk_aac.download]]
    sha256 = "00e12627c2abca417dbae9de64be8a647d88eecb4894e7bb0c53aa21435bb6a5"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v2.0.3+0/libfdk_aac.v2.0.3.x86_64-linux-musl.tar.gz"
[[libfdk_aac]]
arch = "x86_64"
git-tree-sha1 = "5c258fb26c0f3ee0097bb4b3cb219d5f2726de3e"
os = "freebsd"

    [[libfdk_aac.download]]
    sha256 = "ee0d128f617283ca12a1d3f65c27469afe1c8a9a058d5c990304902e5f55d626"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v2.0.3+0/libfdk_aac.v2.0.3.x86_64-unknown-freebsd.tar.gz"
[[libfdk_aac]]
arch = "x86_64"
git-tree-sha1 = "8534fc77f690d6336c7e58fe7c8d213167c8bd17"
os = "windows"

    [[libfdk_aac.download]]
    sha256 = "9a6b60d9715d8f9613df51292c185db77d716e8f1f6c0a8e842c1d526d3f4e44"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v2.0.3+0/libfdk_aac.v2.0.3.x86_64-w64-mingw32.tar.gz"
